#!/bin/bash -x
IFS=$'\n'
if [ $# -ne 1 ]; then
        echo "usage: ${0##*/} <target cue file>"
        exit 1;
fi

CUE_FILE=$1

shnsplit -t "%n - %p - %t" -o flac -f ${CUE_FILE} ${CUE_FILE}.flac || exit 1
rm ${CUE_FILE}
rm ${CUE_FILE%%.flac}.flac



